selftests/filesystems: Fix build of anon_inode_test
The anon_inode_test test fails to build due to attempting to include
a nonexisting overlayfs/wrapper.h:

anon_inode_test.c:10:10: fatal error: overlayfs/wrappers.h: No such file or directory
   10 | #include "overlayfs/wrappers.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~

This is due to 0bd92b9fe538 ("selftests/filesystems: move wrapper.h out
of overlayfs subdir") which was added in the vfs-6.16.selftests branch
which was based on -rc5 and does not contain the newly added test so
once things were merged into vfs.all in the build started failing - both
parent commits are fine.

Fixes: feaa00dbff45a ("Merge branch 'vfs-6.16.selftests' into vfs.all")
Signed-off-by: Mark Brown <broonie@kernel.org>